// Common/core pak APIs and enums
#pragma once
#include <stdint.h>

// global ctx?
//void pak_set_error_printer(struct PakWiFi *ctx, void (*printf)(void *arg, const char *fmt, ...), void *arg);
//static void pak_error(struct Pak)

typedef char _pad_pointer[(sizeof(uintptr_t) - sizeof(uint32_t)) ? 4 : 0];

enum PakErrorCode {
	PAK_PERMISSION_DENIED = -1,
	PAK_UNSUPPORTED = -2,
};

enum PakDeviceType {
	PAK_DEVICE_PROFESSIONAL_CAMERA = 1,
	PAK_DEVICE_ACTION_CAMERA,
	PAK_DEVICE_DASHCAM,
	PAK_DEVICE_SECURITY_CAMERA,
	PAK_DEVICE_BABY_MONITOR,
	PAK_DEVICE_GENERIC_CAMERA,
	PAK_DEVICE_WIFI_SD_CARD,
	PAK_DEVICE_DOORBELL,
	PAK_DEVICE_KITCHEN_APPLIANCE,
	PAK_DEVICE_GENERIC_HOME_DEVICE,
	PAK_DEVICE_HEADPHONES,
	PAK_DEVICE_EARBUDS,
	PAK_DEVICE_GENERIC_AUDIO,
	PAK_DEVICE_GLASSES,
	PAK_DEVICE_GENERIC_TV,
	PAK_DEVICE_SMARTWATCH,
	PAK_DEVICE_GENERIC_MEDICAL_WEARABLE,
	PAK_DEVICE_EXERCISE_MACHINE,
	PAK_DEVICE_DRONE,
	PAK_DEVICE_GENERIC_REMOTE_CONTROL,
	PAK_DEVICE_SCOOTER,
	PAK_DEVICE_BICYCLE,
	PAK_DEVICE_GENERIC_RIDEABLE,
	PAK_DEVICE_AUTOMOTIVE_INFOTAINMENT,
	PAK_DEVICE_AUTOMOTIVE_DIAGNOSTIC,
	PAK_DEVICE_3D_PRINTER,
	PAK_DEVICE_WIFI_ROUTER,
};
