set(CMAKE_EXPORT_COMPILE_COMMANDS 1)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

if(DEFINED ENV{WASI_SDK_PATH} AND EXISTS "$ENV{WASI_SDK_PATH}")
	set(WASI_SDK_PREFIX "$ENV{WASI_SDK_PATH}")
elseif(EXISTS "${CMAKE_CURRENT_LIST_DIR}/wasi-sdk")
	set(WASI_SDK_PREFIX "${CMAKE_CURRENT_LIST_DIR}/wasi-sdk")
elseif(EXISTS "/opt/wasi-sdk")
	set(WASI_SDK_PREFIX "/opt/wasi-sdk")
endif()

set(WASI_TARGET "wasm32-wasip1")

if(WASI_SDK_PREFIX)
	set(CMAKE_SYSROOT "${WASI_SDK_PREFIX}/share/wasi-sysroot")
	set(CMAKE_C_COMPILER "${WASI_SDK_PREFIX}/bin/clang")
	set(CMAKE_CXX_COMPILER "${WASI_SDK_PREFIX}/bin/clang++")
	set(CMAKE_LINKER "${WASI_SDK_PREFIX}/bin/wasm-ld")
	set(CMAKE_AR "${WASI_SDK_PREFIX}/bin/llvm-ar")
	set(CMAKE_NM "${WASI_SDK_PREFIX}/bin/llvm-nm")
	set(CMAKE_RANLIB "${WASI_SDK_PREFIX}/bin/llvm-ranlib")
	set(WASI_CXX_EXTRA "-fno-exceptions")
	set(CMAKE_CXX_STANDARD_LIBRARIES "-lc++ -lc++abi -lc -lwasi-emulated-getpid")
else()
	if(EXISTS "/usr/share/wasi-sysroot")
		set(CMAKE_SYSROOT /usr/share/wasi-sysroot)
	endif()
	set(CMAKE_C_COMPILER "/usr/bin/clang")
	set(CMAKE_CXX_COMPILER "/usr/bin/clang++")
	set(CMAKE_LINKER "/usr/bin/wasm-ld")
	set(CMAKE_AR "/usr/bin/llvm-ar")
	set(CMAKE_NM "/usr/bin/llvm-nm")
	set(CMAKE_RANLIB "/usr/bin/llvm-ranlib")
	set(WASI_CXX_EXTRA "")
endif()

set(WASI_TARGET_FLAGS "--target=${WASI_TARGET} -D_WASI_EMULATED_GETPID -include ${CMAKE_CURRENT_LIST_DIR}/include/shim_sockets.h")

set(CMAKE_C_FLAGS "${WASI_TARGET_FLAGS}" CACHE INTERNAL "")
set(CMAKE_C_COMPILER_TARGET "${WASI_TARGET}")
set(CMAKE_CXX_FLAGS "${WASI_TARGET_FLAGS} ${WASI_CXX_EXTRA}" CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_TARGET "${WASI_TARGET}")

set(CMAKE_EXE_LINKER_FLAGS "-nostartfiles -Wl,--export-table,--no-entry,--export=get_module,--allow-undefined-file=${CMAKE_CURRENT_LIST_DIR}/symbols.txt" CACHE INTERNAL "")
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--export-table,--no-entry,--allow-undefined-file=${CMAKE_CURRENT_LIST_DIR}/symbols.txt" CACHE INTERNAL "")
set(CMAKE_OBJDUMP "/usr/bin/llvm-dwarfdump" CACHE INTERNAL "")
set(PKG_CONFIG_EXECUTABLE "/bin/false")

set(CMAKE_C_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")
